site_name: KnzkApp
site_url: https://knzkapp-help.nzws.me
site_description: KnzkAppのヘルプWikiです。
site_author: '@KnzkDev'
repo_url: https://github.com/KnzkDev/KnzkApp-docs
repo_name: KnzkApp-docs
pages:
  - KnzkAppについて: index.md
  - 使い方: using.md
  - FAQ: faq.md
  - Tip:
    - 通知をコンパクトに: tip/notification_compact.md